name: Compile-only configurations

on:
  push:
    branches: 
      - master
      - develop
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - '.github/workflows/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/configurations.yml'

  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - '.github/workflows/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/configurations.yml'

jobs:
  matrix-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

#      - id: get-list
#        uses: Rishabh510/Path-lister-action@master
#        with:
#          path: "test/config/compile-only"
#          type: ".json"
      
      - id: set-matrix
        name: Parse output
        run: python3 -c 'import os, json; print(json.dumps(os.listdir("test/config/compile-only")))' >> $GITHUB_OUTPUT
#        run: echo "${{ steps.get-list.outputs.paths }}" | awk '{out=$1; for(i=2;i<=NF;i++){ out = out","$i }; print "matrix={path:[ "out" ]}"}' >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  check-configurations:
    runs-on: ubuntu-latest
    needs: matrix-generate
    strategy:
      matrix:
        file: ${{ fromJSON(needs.matrix-generate.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Set up
      run: |
        vcpkg/bootstrap-vcpkg.sh
        vcpkg/vcpkg install

    - name: Configure
      run: ./config.sh ${{ matrix.file.path }}

    - name: Make
      run: make

