name: Compile-only configurations

on:
  push:
    branches: 
      - master
      - develop
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - '.github/workflows/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/configurations.yml'

  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - '.github/workflows/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/configurations.yml'

jobs:
  matrix-generate:
    runs-on: ubuntu-latest
    outputs:
      matrix: "[ $(echo ${{ steps.set-matrix.outputs.paths }} | tr ' ' ',') ]"
    steps:
      - uses: actions/checkout@v1

      - id: set-matrix
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "test/config/compile-only"
          type: ".json"

  check-configurations:
    runs-on: ubuntu-latest
    needs: matrix-generate
    strategy:
      matrix:
        file: ${{ fromJSON(needs.matrix-generate.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Set up
      run: |
        vcpkg/bootstrap-vcpkg.sh
        vcpkg/vcpkg install

    - name: Configure
      run: ./config.sh ${{ matrix.file }}

    - name: Make
      run: make

