name: Compile-only configurations

on:
  push:
    branches: 
      - master
      - develop
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - '.github/workflows/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/configurations.yml'

  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - '.github/workflows/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/configurations.yml'

jobs:
  check-configurations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Get python to list the contents of test/config/compile-only in json format
        tests: "${{ fromJSON($(python3 -c 'import os, json; print(json.dumps(os.listdir(\'test/config/compile-only\')))')) }}"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Set up
      run: |
        vcpkg/bootstrap-vcpkg.sh
        vcpkg/vcpkg install

    - name: Configure
      run: ./config.sh test/config/compile-only/${{ matrix.tests.file }}

    - name: Make
      run: make

